### ISSUE TITLE
Errors in the Eagle Board?

### ISSUE THREAD

**Issue by ThomasLengeling** [sparkfun/Transceiver_Breakout-nRF24L01#1]
Thank you for your amazing design and board.

I was looking into the circuit file and I encounter that Eagle says there are a couple of error and overlays in the circuit design. I am wondering if those error messages can be ignored or is it a big problem.

![error](https://user-images.githubusercontent.com/920285/49107227-244c7d00-f253-11e8-906a-d379ec0b8a3d.png)

Thank you for your help.
Thomas

**Comment by nseidle** [comment]
What a blast from the past. I designed this board a long time ago! I'm happy you can get some value from it.

Those overlap errors can be ignored. They are the landing spots for what look like ground test points but I can't figure out who added them or why they are there. The VCC test point overlap also throws an error and it is there so that we can verify the 3.3V regulator is working.

![image](https://user-images.githubusercontent.com/117102/49125261-b2892900-f27c-11e8-8399-ae77887ce7f4.png)

![image](https://user-images.githubusercontent.com/117102/49125291-cd5b9d80-f27c-11e8-9aaf-a550c0253f66.png)

If you have more questions, please let me know.

**Comment by ThomasLengeling** [comment]
great, thank you!, I am designing a circuit with the nRF and your circuit is very useful.
thank you for your response.
